general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 3
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2

    outer_color = rgba(ffffff22)
    inner_color = rgba(00000055)
    font_color = rgba(ffffffff)

    fade_on_empty = false
    placeholder_text = <i>Enter password...</i>

    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = Sans

    position = 0, 80
    halign = center
    valign = center
}
